### ISSUE TITLE
about dataset and training

### ISSUE THREAD

**Issue by zzzhhh1031** [Anirudh257/strm#1]
Hello! Thank you for your excellent work. I now have a dataset of hmdb51, how to split it according to the splits you gave. And how do you modify the sh file for training afterwards? Can you elaborate, look forward to your reply, thank you very much!

**Comment by Anirudh257** [comment]
1) Download the HMDB videos from its site and process the required frames.

2) Sh file is specifically used for training on HPC clusters. If you are running locally, just run the python command.
