### ISSUE TITLE
datasets and ValueError: Sample larger than population or is negative

### ISSUE THREAD

**Issue by tcc-power** [Anirudh257/strm#10]
Hi there I have organized my hmdb datasets into jpgs like this：

> ./video_datasets/data/hmdbjpg/brush_hair/April_09_brush_hair_u_nm_np1_ba_goo_0/April_09_brush_hair_u_nm_np1_ba_goo_0_1.jpg

> ./video_datasets/data/hmdbjpg/brush_hair/April_09_brush_hair_u_nm_np1_ba_goo_0/April_09_brush_hair_u_nm_np1_ba_goo_0_2.jpg
...
and my training command is
`python3 run.py -c checkpoint_dir_hmdb/ --query_per_class 4 --shot 5 --way 5 --trans_linear_out_dim 1152 --test_iters 10000 --dataset hmdb --split 3 -lr 0.0001 --method resnet50 --img_size 224 --scratch new --num_gpus 1 --print_freq 1 --save_freq 10000 --training_iterations 20010 --temp_set 2
`
the error is :
`File "/home/tcc/anaconda3/envs/torch1.9/lib/python3.8/random.py", line 363, in sample
 raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative`

have you met this issue before, how can i solve it?

**Comment by Anirudh257** [comment]
You will need to check the https://github.com/Anirudh257/strm/blob/main/video_reader.py and the names of the files in https://github.com/Anirudh257/strm/tree/main/splits/hmdb_ARN and check if they match or not.

**Comment by 16422004** [comment]
> You will need to check the https://github.com/Anirudh257/strm/blob/main/video_reader.py and the names of the files in https://github.com/Anirudh257/strm/tree/main/splits/hmdb_ARN and check if they match or not.

Thank you, what does each line in trainlist03.txt mean, an avi video or a video frame directory
