### ISSUE TITLE
Some confusion

### ISSUE THREAD

**Issue by Clearlove1111** [Anirudh257/strm#11]
We used ffmpeg to extract the video in hmdb51 at 8 fps, the number of iterations was set to 40000, and the rest of the parameters were the default parameters in your code, and I've read the previous issue and preprocessed the dataset as mentioned,but did not get the expected accuracy, the difference was about 4%, what may be the reason?
Thank you very much！

**Comment by Anirudh257** [comment]
Hi, 
    I think that the fps is too low here, affecting the quality of data. You can use something higher and check the quality of the images. Then, you may need to train again up to 10K/20K/30K iterations. You can also use ViT backbone setting to get a better result.
