### ISSUE TITLE
Questions about FLOPs

### ISSUE THREAD

**Issue by eveleslie** [Anirudh257/strm#12]
Hello, there is a reference to this sentence   **_Moreover, it is worth mentioning that our STRM is comparable to TRX in terms of compute, requiring only ∼ 4% additional FLOPs_** in your paper. Can I ask you what is the exact value of FLOPs for your model?

**Comment by Anirudh257** [comment]
Hi @eveleslie, you can use https://github.com/cszn/KAIR to compute the FLOPs
