### ISSUE TITLE
Question about 1-shot 

### ISSUE THREAD

**Issue by ycbilge** [Anirudh257/strm#13]
Hi,
Thanks for sharing the code. I tried to get experimental results in 1-shot for both 5-way and 20-way settings. The accuracy is always low for both training and test set and does not improve through the iterations after a couple of iterations. I think I am using the wrong parameters. Could you please share your parameters for 1-shot results? Have you get any results for 20-way settings? Moreover if you have any suggestions/tips on getting results in 1-shot for both 5-way and 20-way, it would be highly appreciated. 
In the paper under the experiments of different number of support samples, there is a sentence: "additional results are provided in the supplementary", but I couldn't find these results in the supplementary. I think I am missing something so I would be very happy if you could direct me to those additional results.
Thanks again for the great work.
Best,

**Comment by Anirudh257** [comment]
Hi, @ycbilge I don't have results for 20-way settings. For 5-way, you can follow the same steps as mentioned in the paper. You need to just change **way** to 1 here: https://github.com/Anirudh257/strm/blob/main/scripts/eval_strm_ssv2.sh

**Comment by caidhome** [comment]
> Hi, Thanks for sharing the code. I tried to get experimental results in 1-shot for both 5-way and 20-way settings. The accuracy is always low for both training and test set and does not improve through the iterations after a couple of iterations. I think I am using the wrong parameters. Could you please share your parameters for 1-shot results? Have you get any results for 20-way settings? Moreover if you have any suggestions/tips on getting results in 1-shot for both 5-way and 20-way, it would be highly appreciated. In the paper under the experiments of different number of support samples, there is a sentence: "additional results are provided in the supplementary", but I couldn't find these results in the supplementary. I think I am missing something so I would be very happy if you could direct me to those additional results. Thanks again for the great work. Best,

Hi, I have the same problem as you. How did you finally set the parameters of 5-way 1-shot?

**Comment by caidhome** [comment]
@ycbilge Hi, I have the same problem as you. How did you finally set the parameters of 5-way 1-shot

> Hi, Thanks for sharing the code. I tried to get experimental results in 1-shot for both 5-way and 20-way settings. The accuracy is always low for both training and test set and does not improve through the iterations after a couple of iterations. I think I am using the wrong parameters. Could you please share your parameters for 1-shot results? Have you get any results for 20-way settings? Moreover if you have any suggestions/tips on getting results in 1-shot for both 5-way and 20-way, it would be highly appreciated. In the paper under the experiments of different number of support samples, there is a sentence: "additional results are provided in the supplementary", but I couldn't find these results in the supplementary. I think I am missing something so I would be very happy if you could direct me to those additional results. Thanks again for the great work. Best,
