### ISSUE TITLE
dataset question

### ISSUE THREAD

**Issue by ChengHSUHSU** [Anirudh257/strm#16]
Hello,
There are some question about the code.

I use the command, but terminal return the error.
So, the file "hmdb51_256q5.zip", I cannot find it.

Thanks,

<img width="677" alt="截圖 2022-11-04 下午5 42 07" src="https://user-images.githubusercontent.com/76766937/199942134-306e8f50-68de-4ca6-82cb-3ccbdfd41d80.png">

<img width="1207" alt="截圖 2022-11-04 下午5 41 30" src="https://user-images.githubusercontent.com/76766937/199942006-a3f9a2de-7d4e-491a-8099-dfee2722f7f0.png">

**Comment by Anirudh257** [comment]
Hi @ChengHSUHSU Please check the path as mentioned here in https://github.com/Anirudh257/strm/blob/54368fe94ac76d495f018b28a0d8d19dcdc23504/run.py#L170

and 

https://github.com/Anirudh257/strm/blob/54368fe94ac76d495f018b28a0d8d19dcdc23504/run.py#L147

and update the paths to the datasets appropriately.

**Comment by ChengHSUHSU** [comment]
@Anirudh257 
Hi,
Thank your reply soon,
I want to know how to install hmdb51_256q5.zip,
I have surveyed HMDB dataset, like this (https://paperswithcode.com/dataset/hmdb51)
but I cannot find zip file.

Thanks

**Comment by Anirudh257** [comment]
Hi @ChengHSUHSU , you can follow the steps of sampling  and perform the preprocessing steps as given in my paper and make your own zip file.
