### ISSUE TITLE
parameter scratch

### ISSUE THREAD

**Issue by Liu-arch** [Anirudh257/strm#17]
Hello, I didn't quite understand the meaning of the scratch parameter, why three different args.scratch were created, and if bp is meant to modify two parameters, then what is the difference between new and bc. Also, this will allow multiple copies of the data to be copied to different folders

**Comment by Anirudh257** [comment]
Hi @Liu-arch, you can remove the **bc** and **bp** parameters. Just use **new**. new contains the name of the folder containing the path to the datasets and split files.
