### ISSUE TITLE
multi-label prediction

### ISSUE THREAD

**Issue by ChengHSUHSU** [Anirudh257/strm#18]
Hi, 
this is nice work.
the paper model, strm is single label prediction.
how to predict multi label data??

**Comment by Anirudh257** [comment]
Hi @ChengHSUHSU Thanks for your kind words. STRM works for single-label prediction only. You may need to make modifications in the video_reader.py first to correct the data loading and change the model.py too to extend it to the multi-label case but I haven't tried it yet.
