### ISSUE TITLE
the number of frames chosen

### ISSUE THREAD

**Issue by Liu-arch** [Anirudh257/strm#20]
Hello, Can you tell me how you extracted the jpg images from the avi format video and how many frames are chose for a video? The git project from trx gets an empty folder.

**Comment by Anirudh257** [comment]
Hi, I used ffmpeg to extract the frames.

**Comment by Liu-arch** [comment]
How many frames are chose for a video? Is this fixed？Or 1 frame for 1 second？

**Comment by Anirudh257** [comment]
You can use 30 fps
