### ISSUE TITLE
Accuracy issues

### ISSUE THREAD

**Issue by Liu-arch** [Anirudh257/strm#21]
Hello, I currently tested only one dataset UCF101 by loading your model but did not get an accuracy of 96.9, only 96.308. I have a feeling it may be a dataset issue or a luck issue, so I would like to get the code you used in building the dataset.

**Comment by Anirudh257** [comment]
Hi, I just followed the same steps as mentioned in the paper.

**Comment by M77827** [comment]
> Hello, I currently tested only one dataset UCF101 by loading your model but did not get an accuracy of 96.9, only 96.308. I have a feeling it may be a dataset issue or a luck issue, so I would like to get the code you used in building the dataset.

Hello,now can you reproduce the accuracy of the paper?
