### ISSUE TITLE
the Kinetics-100 dataset

### ISSUE THREAD

**Issue by waw123456** [Anirudh257/strm#24]
Nice to meet you bro, I recently search for the dataset Kinetics, but always miss a lot videos, it takes me a lot time, Can you share the Kinetics-100 dataset?Thanks! My mail is 156472065@qq.com. Thank you, Please!

**Comment by AnnXie2001** [comment]
I also need that one ,could you send me a copy to 1106426282@qq.com pls? Thanks a lot!

**Comment by ssp-seven** [comment]
> 我也需要这个，你能发一份给我到[1106426282@qq.com](mailto:1106426282@qq.com)吗？非常感谢！

Hello, may I ask if you have received the results?
