### ISSUE TITLE
Five categories of samples are missing in the Kinetics-100 dataset;

### ISSUE THREAD

**Issue by waw123456** [Anirudh257/strm#26]
Hi, Anirudh, I am here again. 
Compared to the splits of kinetics, I found my kinetics dataset miss 5 categories, they are "cleaning_floor" ,"dying_hair", "opening_bottle", "using_computer" in the train set, and "hurling_(support)" int the test set. 
Also, there are five more categories, they are "falling_off_bike","opening_door","playing_darts","tapping_guitar" and "walking_the_door".
Can you send me the missed 5 categories, Please！ Or should I replace the splits with these categories?

**Comment by Anirudh257** [comment]
Hi @waw123456 Kinetics is sourced from Youtube and hence the data can be missing when the videos get removed or are made private. You can try creating a new split as well.
