### ISSUE TITLE
When training ,loss is nan

### ISSUE THREAD

**Issue by Wickked-swag** [Anirudh257/strm#28]
Hello, I have been running your code recently, but there are some problems that cannot be solved. I hope you can help me.
When I was training, the loss value would be nan value. After debugging, I found that after a certain number of rounds of input to resnet, the output feature value would become nan. I don't know why this happened or how to solve it. Can you help me?
<img width="1159" alt="1" src="https://user-images.githubusercontent.com/60918390/234526956-ef147a4a-d742-4037-84c4-24cff7cb0349.png">

**Comment by Anirudh257** [comment]
Hi, please check the preprocessing steps before loading the images into the model.
