### ISSUE TITLE
About train_output.log

### ISSUE THREAD

**Issue by eveleslie** [Anirudh257/strm#3]
Hi Anirudh!
I'm sorry I forgot to reply to you in email last time, but after reading your reply I went and compiled the ssv2 dataset and it's ready.
If you need it, I can provide you with the download address of the file, and if anyone asks about this dataset in the future, you can provide it directly.
I would also like to bother you again, when I ran the code, the program prompted me that a file could not be found.
`train_logger = setup_logger('training_accuracy', '. /runs_trx_ssv2_tempset_2_gamma_hier_patch_16_lin_bot_mlp_new_dist_loss_clsw_relu_no_pe_drop_frame_mlp_mix_run1/train_output.log')`
`eval_logger = setup_logger('Evaluation_accuracy', './runs_trx_ssv2_tempset_2_gamma_hier_patch_16_lin_bot_mlp_new_dist_loss_clsw_relu_no_pe_drop_frame_mlp_mix_run1/eval_output.log')  `
They are located in the **_run.py line32 line 35_**
I would like to ask what are these two files? Are you comfortable providing these two files?
Thank you so much!

**Comment by Anirudh257** [comment]
Hi, thanks but I don't need the dataset anymore. Also, these log names are not special. Just read this: https://realpython.com/python-logging/. Give a unique name to the folder where you want to store the final run files.

**Comment by project891** [comment]
Hi, can you provide a dataset?

**Comment by Anirudh257** [comment]
Hi @project891 you can download the datasets from the respective links and follow the steps as given in the paper. I don't have access to the dataset anymore.

**Comment by project891** [comment]
Hi, can you provide a link to the processed dataset? Thank you so much.

**Comment by Anirudh257** [comment]
Sorry, I don't have the link @project891
