### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 0)

### ISSUE THREAD

**Issue by CS-FantaC** [Anirudh257/strm#38]
envs/env_ani/lib/python3.9/site-packages/torch/_utils.py", line 722, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.

video_reader.py", line 343, in __getitem__
    target_set, target_labels, real_target_labels = zip(*t)
ValueError: not enough values to unpack (expected 3, got 0)

I tried to evaluate on HMDB51 with comand:  nohup python3 run.py -c checkpoint_dir_hmdb_425/ --query_per_class 4 --shot 5 --way 5 --trans_linear_out_dim 1152 --test_iters 10000 --dataset hmdb --split 3 -lr 0.0001 --img_size 224 --scratch new --num_gpus 2 --method resnet50 --save_freq 10000 --print_freq 1 --training_iterations 20010 --temp_set 2 --test_model_only True --test_model_path checkpoints/checkpoint_hmdb.pt > 425.log 2>&1 &
I check the log file and when it finish Task [341/20010], Train Loss: 0.2502708, Train Accuracy: 0.9444445,the error mentioned above occurred.How can I solve it , does it have something to do with the HMDB51 dataset I got is different from yours?
Or is the default dataloader parameter num_workers=10  too big?

**Comment by M77827** [comment]
Can you leave an email to discuss it

**Comment by Anirudh257** [comment]
Your dataset seems to be corrupted. Make it again and retry.
