### ISSUE TITLE
Some videos are missing in the Kinetics Dataset.

### ISSUE THREAD

**Issue by Shunli-Wang** [Anirudh257/strm#4]
Thank you for shearing your code. It's a wonderful work!

1. I create the **FSL-Kinetics** from **Kinetics-400** dataset following the `kinetics_CMN/*.txt` splits. I found that some videos are missing in **Kinetics-400**. Could you please provide the links of these videos?
2. BTW, I use the incomplete **FSL-Kinetics** retrain your model and get the following result. This result is slightly lower than that reported in the paper (86.7). It's this caused by these missing videos?
```python
{'kinetics': {'accuracy': 85.38, 'confidence': 0.32, 'loss': 0.00029}}
```
Looking forward to your replay!

**Comment by Anirudh257** [comment]
@Shunli-Wang Unfortunately, the Kinetics dataset is sourced from online Youtube videos that can get taken down or become private. You can try training for more training iterations(10K/20K/30K) and use the lr as specified in: https://github.com/Anirudh257/strm/blob/main/scripts/run_strm_kin.sh
