### ISSUE TITLE
There is a gap with the report in hmdb

### ISSUE THREAD

**Issue by Brave-peng** [Anirudh257/strm#7]
Thank you for sharing your code. It's a wonderful work!
When I run test code in hmdb using checkpoint you given, I get the accuracy that is 74%, smaller than the report(77.3).
I wonder if you could tell me the possible reasons?

this is the script code I used.
`python3 run.py -c checkpoint_dir_hmdb/ --query_per_class 4 --shot 5 --way 5 --trans_linear_out_dim 1152 --test_iters 10000 --dataset hmdb --split 3 -lr 0.0001 --img_size 224 --scratch new --num_gpus 4 --method resnet50 --save_freq 10000 --print_freq 1 --training_iterations 20010 --temp_set 2`

**Comment by Anirudh257** [comment]
@Brave-peng I am glad that you liked the work. You can do:

1) Check if the dataset was created properly and process HMDB again following the steps in my paper and TRX.

2) Train for more iterations like 30K/40K, etc.

Check the paper for VIT-backbone results as well.

**Comment by M77827** [comment]
> Thank you for sharing your code. It's a wonderful work! When I run test code in hmdb using checkpoint you given, I get the accuracy that is 74%, smaller than the report(77.3). I wonder if you could tell me the possible reasons?
> 
> this is the script code I used. `python3 run.py -c checkpoint_dir_hmdb/ --query_per_class 4 --shot 5 --way 5 --trans_linear_out_dim 1152 --test_iters 10000 --dataset hmdb --split 3 -lr 0.0001 --img_size 224 --scratch new --num_gpus 4 --method resnet50 --save_freq 10000 --print_freq 1 --training_iterations 20010 --temp_set 2`

Hello,now can you reproduce the accuracy of the paper?
