### ISSUE TITLE
question in extracting frames

### ISSUE THREAD

**Issue by hitomizzz** [Anirudh257/strm#9]
hi, thank you for your excellent work.
I'm also interested in this research field, but I have several questions in preparing the dataset.

1. how do you extract the videos into frames, did you use ffmpeg?
2. if you used ffmpeg to extract the frames, can you share me with the detail of it?  Such as how many fps(-r) do you extract each video and the quality (-q:v).

Thank you so much!

**Comment by Anirudh257** [comment]
@hitomizzz Thanks for your interest in our work.

1. Yes, I used FFmpeg.

2. Please, follow the TRX paper for details: 
![image](https://user-images.githubusercontent.com/16001446/179163310-45662c27-d8ed-410b-b99f-c925fd444185.png)

The paper can be found here: https://openaccess.thecvf.com/content/CVPR2021/papers/Perrett_Temporal-Relational_CrossTransformers_for_Few-Shot_Action_Recognition_CVPR_2021_paper.pdf
